<?php

// This file contains the current being tracked configurations.

$tracked = array (
  'field.entityform.field_email.or_amento_e_contato' => '2ff63b86f58eee83ac3f3767783e87f726bf041b',
  'field.entityform.field_message.or_amento_e_contato' => '2926dafca77889235a0cf3e59e840509a11154ad',
  'field.entityform.field_name.or_amento_e_contato' => '9634d91f59ee222ec33a8986a1348da5e3d9741d',
  'variable.theme_default' => '7ec42b8d2798e8199908750f7bd6f37666451a8d',
  'entityform_type.or_amento_e_contato' => '558583ecce129430847236b9bcace28883a43736',
);


// The following modules are required to run the configurations of this file.

$modules = array(
  'entity',
  'entityform',
  'field_sql_storage',
  'text',
);
